template: 'facelessuser:master-labels:labels.yml:master'

# Wildcard labels

brace_expansion: true
extended_glob: true

rules:
  - labels: [infrastructure]
    patterns: ['*|-@(*.md|*.py|*.sublime-@(keymap|menu|settings|commands))', '.github/**']

  - labels: [source]
    patterns: ['st[0-9]/mdpopups/**|**/*.sublime-@(keymap|menu|settings|commands)|-tests']

  - labels: [docs]
    patterns: ['**/*.md|docs/**']

  - labels: [tests]
    patterns: ['tests/**']

  - labels: [code-highlight]
    patterns: ['st[0-9]/mdpopups/mdx/**|st[0-9]/mdpopups/@(st_@(code|pygments)_highlight.py|)']

  - labels: [API]
    patterns: ['st[0-9]/mdpopups/__init__.py']

  - labels: [code-highlight, languages]
    patterns: ['st[0-9]/mdpopups/st_mapping.py']

  - labels: [scheme-support]
    patterns: ['st[0-9]/mdpopups/st_@(color_scheme_matching|scheme_template).py|css/**']

  - labels: [images]
    patterns: ['st[0-9]/mdpopups/@(png|imagetint|colorbox).py']

  - labels: [colors]
    patterns: ['st[0-9]/mdpopups/@(rgba|x11colors).py']

  - labels: [settings]
    patterns: ['**/*.sublime-@(keymap|menu|settings|commands)']

labels:
- name: code-highlight
  color: subcategory
  description: Related to code highlighting.

- name: API
  color: subcategory
  description: Related to the API.

- name: languages
  color: subcategory
  description: Related to supported code lanugage mapping for highlighter.

- name: scheme-support
  color: subcategory
  description: Related to handling color schemes.

- name: images
  color: subcategory
  description: Related to image processing/creation.

- name: colors
  color: subcategory
  description: Related to color handling.

- name: settings
  color: subcategory
  description: Related to Sublime settings files.
