# Wildcard labels

brace_expansion: true
extended_glob: true

rules:
  - labels: [infrastructure]
    patterns: ['*|-@(*.md|*.py|*.sublime-@(keymap|menu|settings|commands))', '.github/**']

  - labels: [source]
    patterns: ['st[0-9]/mdpopups/**']

  - labels: [docs]
    patterns: ['**/*.md|docs/**']

  - labels: [tests]
    patterns: ['tests/**']

  - labels: [code-highlight]
    patterns: ['st[0-9]/mdpopups/mdx/**|st[0-9]/mdpopups/@(st_@(code|pygments)_highlight.py|)']

  - labels: [API]
    patterns: ['st[0-9]/mdpopups/__init__.py']

  - labels: [code-highlight, languages]
    patterns: ['st[0-9]/mdpopups/st_mapping.py']

  - labels: [scheme-support]
    patterns: ['st[0-9]/mdpopups/st_@(color_scheme_matching|scheme_template).py|css/**']

  - labels: [images]
    patterns: ['st[0-9]/mdpopups/@(png|imagetint|colorbox).py']

  - labels: [colors]
    patterns: ['st[0-9]/mdpopups/@(rgba|x11colors).py']

  - labels: [settings]
    patterns: ['**/*.sublime-@(keymap|menu|settings|commands)']

# Triage

triage_add: 'triage'
triage_skip: ['skip-triage']
triage_remove: ['confirmed']

# Review

review_add: 'needs-review'
review_skip: ['skip-review']
review_remove: ['approved']

# WIP

wip:
  - work-in-progress
  - needs-review
  - needs-decision
  - needs-confirmation
  - requires-changes
  - rejected
  - duplicate
  - invalid
  - triage
  - wontfix

# LGTM

lgtm_add:
  pull_request: [approved]
  issue: []

lgtm_remove:
  - work-in-progress
  - needs-review
  - needs-decision
  - needs-confirmation
  - requires-changes
  - rejected
  - duplicate
  - invalid
  - triage
  - wontfix

# Label management

delete_labels: true

colors:
    bug: '#c45b46'
    feature: '#7b17d8'
    enhancement: '#0b9e9e'
    support: '#efbe62'
    maintenance: '#b2ffeb'
    category: '#709ad8'
    subcategory: '#bfd4f2'
    pending: '#f0f49a'
    rejected: '#f7c7be'
    approved: '#beed6d'
    low: '#dddddd'
    bot: '#000000'

labels:
- name: bug
  color: bug
  description: Bug report.

- name: feature
  color: feature
  description: Feature request.

- name: enhancement
  color: enhancement

- name: maintenance
  color: maintenance
  description: Maintenance chore.

- name: support
  color: support
  description: Support request.

- name: tests
  color: category
  description: Related to testing.

- name: infrastructure
  color: category
  description: Related to project infrastructure.

- name: source
  color: category
  description: Related to source code.

- name: docs
  color: category
  description: Related to documentation.

- name: code-highlight
  color: subcategory
  description: Related to code highlighting.

- name: API
  color: subcategory
  description: Related to the API.

- name: languages
  color: subcategory
  description: Related to supported code lanugage mapping for highlighter.

- name: scheme-support
  color: subcategory
  description: Related to handling color schemes.

- name: images
  color: subcategory
  description: Related to image processing/creation.

- name: colors
  color: subcategory
  description: Related to color handling.

- name: settings
  color: subcategory
  description: Related to Sublime settings files.

- name: more-info-needed
  color: pending
  description: More information is required.

- name: needs-confirmation
  color: pending
  description: The alleged behavior needs to be confirmed.

- name: needs-decision
  color: pending
  description: A decision needs to be made regarding request.

- name: confirmed
  color: approved
  description: Confirmed bug report or approved feature request.

- name: maybe
  color: low
  description: Pending approval of low priority request.

- name: duplicate
  color: rejected
  description: The issue has been previously reported.

- name: wontfix
  color: rejected
  description: The issue will not be fixed for the stated reasons.

- name: invalid
  color: rejected
  description: Invalid report (user error, upstream issue, etc).

- name: triage
  color: pending
  description: Issue needs triage.

- name: work-in-progress
  color: pending
  description: A partial solution. More changes will be coming.

- name: needs-review
  color: pending
  description: Needs to be reviewed and/or approved.

- name: requires-changes
  color: pending
  description: Awaiting updates after a review.

- name: approved
  color: approved
  description: The pull request is ready to be merged.

- name: rejected
  color: rejected
  description: The pull request is rejected for the stated reasons.

- name: skip-triage
  color: bot
  description: Tells bot to not tag a new issue with 'triage'.

- name: skip-review
  color: bot
  description: Tells bot to not tag a reviews with 'needs-review'.
