language: python
python:
  - "3.3"
install:
  - pip install "flake8<3"
  - pip install flake8-docstrings
  - pip install flake8-putty
  - pip install pep8-naming
  - pip install mkdocs
  - pip install mkdocs-material
  - pip install pymdown-extensions
  - pip install pygments
addons:
  apt:
    packages:
      - aspell
      - aspell-en
script:
  - flake8 .
  - python tests/spellcheck.py
